# -*- coding: utf-8 -*-
"""PronosticoUnidadesDolar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12x43eLeq8jKXQjEtlhdycR5ldsZ82AIN
"""

import pandas as pd
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
import statsmodels.formula.api as smf, statsmodels.tsa.api as smt, statsmodels.api as sm
import scipy.stats as scs

data=pd.read_csv("casacambio 4 tms.csv")

series=pd.DataFrame()

series["semana"]=data["semana"]

series["dolaresVendidos"]=data["total de dolares vendidos"]

series

series.dolaresVendidos.plot()

from statsmodels.tsa.api import ExponentialSmoothing

def suavizado_exponencial(series,alpha):
  es1 = ExponentialSmoothing((series), seasonal_periods=48,
                             trend='add',seasonal='add').fit()
  ## pronostico
  es2 = es1.forecast(len(series)//4)
  print(es2)
  series.plot(kind='line',figsize=(15,7))
  es2.plot(kind='line')
  plt.xlabel('Semanas')
  plt.ylabel('Cantidad de dolar vendidos')
  plt.title("Dolares vendidos por semana")

suavizado_exponencial(series.dolaresVendidos,0.3)